spring:
  application:
    name: UserAdminApplication
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/useradmindb           # Container 마다 고유한 Port를 가짐
    username: root
    password: moon
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20      # 최대 커넥션 풀 사이즈
      minimum-idle: 10           # 최소 유휴 커넥 수
      connection-timeout: 30000  # 연결타임아웃(ms)
      idle-timeout: 600000       # 유휴 커넥션 타임아웃 (ms)
      max-lifetime: 1800000      # 커넥션의 최대 수명 (ms)
      validation-timeout: 5000   # 커넥션 유효성 검사 타임아웃 (ms)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      password: moon

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: TRACE



server:
  port: ${SERVER_PORT:8080}  # 기본은 8080이지만, env에 따라 덮어쓰기 가능